# Configuração para Coolify - Backend Agenda
# Este arquivo pode ser usado para configurar o deploy no Coolify

version: '3.8'

services:
  agenda-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
        - VERSION=${VERSION:-latest}
    container_name: agenda-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - PORT=3001
      - DB_HOST=${DB_HOST:-agenda-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_DATABASE=${DB_DATABASE:-agenda_db}
      - JWT_SECRET=${JWT_SECRET:-da0f624b767fc436623e9a8485e42fbe1e303478333f7a0ac9ced9db6c4ec46d69bc676c2e2fee055591456b624b85f3f485f66573e31d161ebb5328f5906b3f}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.framework=nestjs"
      - "coolify.language=typescript"
    networks:
      - coolify-network

networks:
  coolify-network:
    external: true 